language: cpp

os:
  - linux

compiler:
  - gcc
  - clang
  
addons:
  apt:
    sources:
    - llvm-toolchain-precise
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - clang-3.7
    - valgrind
    - python3

before_install:
  - sudo apt-get update

install: 
  - pip install --user cpp-coveralls
  - gem install coveralls-lcov	

before_script:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
  - $CXX --version
  - echo $CXX 

script:
  - make
  - make tgr
  - make ut

after_success:
  - coveralls --exclude UT --exclude cxxtest --exclude unittest.cpp --gcov-options '\-lp'
  - bash <(curl -s https://codecov.io/bash)