language: cpp

os:
  - linux

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - gcc-4.8
    - python3
	
compiler:
  - gcc
  - clang

before_install:
  - pip install --user cpp-coveralls
  
script:
  - make
  - make tgr
  - ./configure --enable-gcov && make && make check
  - make ut

after_success:
  - coveralls --exclude UT --exclude cxxtest --gcov-options '\-lp'
