language: cpp

os:
  - linux

compiler:
  - gcc
  - clang
  
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - valgrind
    - gcov

before_install:

install: 
  - gem install coveralls-lcov	
  
before_script:
  - $CXX --version
  - echo $CXX 

script:
  - make
  - make tgr
  - make ut

after_success:
  - coveralls --exclude UT --exclude cxxtest --gcov-options '\-lp'
