language: cpp

os:
  - linux

compiler:
  - gcc
  - clang

before_install:
  - pip install --user cpp-coveralls
  
script:
  - make
  - make tgr
  - ./configure --enable-gcov && make ut
  - make ut

after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
