language: cpp

os:
  - linux

compiler:
  - gcc
  
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - valgrind
      - python3
  coverity_scan:
    project:
      name: "Cherep07/TrafficGenerator"
      description: "<Your project description here>"
    notification_email: cherepanov.artyom@gmail.com
    build_command_prepend: "make"
    build_command:   "make ut"
    branch_pattern: coverity_scan

before_install:
  - sudo apt-get update

install: 
  - pip install --user cpp-coveralls
  - gem install coveralls-lcov	

before_script:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - $CXX --version
  - echo $CXX 

script:
  - make
  - make tgr
  - make ut

after_success:
  - coveralls --exclude UT --exclude cxxtest --exclude unittest.cpp --gcov-options '\-lp'
  - bash <(curl -s https://codecov.io/bash)